version: '3.4'
services:
  db:
    image: miguel/mysql-rest_spring_boot
    command: mysqld --default-authentication-plugin=mysql_native_password
    working_dir: /dockerMySQL
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: rest_spring_boot
    ports:
      - "3308:3306"
    networks:
      - rest-network
  resfull:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - . resfull
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - rest-network
networks:
  rest-network:
    driver: bridge